SimulacaoCompra/Controllers/ComprasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SimulacaoCompra.Models;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;


namespace SimulacaoCompra.Controllers
{
    public class ComprasController : Controller
    {
        private readonly BancoDbContext _context;

        public ComprasController(BancoDbContext context)
        {
            _context = context;
        }
        public string NameSort { get; set; }
        public string DateSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }

        public PaginatedList<Compra> Compras { get; set; }

        // GET: Compras inicializa a pagina inicial de compras retornando de modo atualizado a data atual.
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {

            TempData["Message"] = "Olá, Seja bem vindo(a) ao simulador de compras, Hoje é dia: " + DateTime.Today.ToString("dd/MM/yyyy");

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var compras = from c in _context.Compras
                          select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                compras = compras.Where(c => c.NomeDaCompra.Contains(searchString)
                                       || c.TipoCalculo.Contains(searchString)
                                       || c.Categoria.Contains(searchString));
            }


            switch (sortOrder)
            {
                case "name_desc":
                    compras = compras.OrderByDescending(c => c.NomeDaCompra);
                    break;
                case "Date":
                    compras = compras.OrderBy(c => c.Datacompra);
                    break;
                case "date_desc":
                    compras = compras.OrderByDescending(s => s.Datacompra);
                    break;
                default:
                    compras = compras.OrderBy(s => s.Categoria);
                    break;
            }

            int pageSize = 3;
            return View(await PaginatedList<Compra>.CreateAsync(
                compras.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .SingleOrDefaultAsync(m => m.Idcompra == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idcompra,NomeDaCompra,Valortotal,Valorjuros,Qtdparcelas,Datacompra,Valorparcela,TipoCalculo,Categoria")] Compra compra)
        {

            // Inicia-se aqui a condição do tipo do calculo escolhido pelo usuário sendo de juros simples ou composto.
            try
            { // calculo do juros Simples
                if ((ModelState.IsValid) && (compra.Datacompra >= DateTime.Today) && (compra.TipoCalculo == "J.Simples"))
                {
                    _context.Add(compra);
                    compra.Valorparcela = compra.Valortotal * compra.Valorjuros + compra.Valortotal;
                    compra.Valorparcela /= compra.Qtdparcelas;
                    await _context.SaveChangesAsync();
                    TempData["Salvo"] = "A simulação foi salva com sucesso, o valor da sua parcela em " + compra.Qtdparcelas + "X é de R$ " + compra.Valorparcela.ToString("0.00");
                    return RedirectToAction(nameof(Index));
                }


                // calculo do juros Composto
                else if ((ModelState.IsValid) && (compra.Datacompra >= DateTime.Today) && (compra.TipoCalculo == "J.Composto"))
                {

                    _context.Add(compra);
                    double M; //montante
                    double capital = Convert.ToDouble(compra.Valortotal); //capital
                    double taxa = Convert.ToDouble(compra.Valorjuros);//taxa juros
                    double Qtd = Convert.ToDouble(compra.Qtdparcelas);//parcela


                    M = capital * Math.Pow((1 + taxa), Qtd);//Formula Juros Composto


                    compra.Valorparcela = Convert.ToDecimal(M);
                    compra.Valorparcela /= compra.Qtdparcelas;

                    await _context.SaveChangesAsync();
                    TempData["Salvo"] = "A simulação foi salva com sucesso, o valor da sua parcela em " + compra.Qtdparcelas + "X é de R$ " + compra.Valorparcela.ToString("0.00");
                    return RedirectToAction(nameof(Index));

                }


                else
                {
                    TempData["ErroSalvar"] = "A data da compra ou serviço deve ser para data atual ou posterior!";
                    return View("Create");
                }

            } //Tratamento de exceção
            catch (Exception)
            {
                return View("Error");
            }
            finally
            {

            }

        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.SingleOrDefaultAsync(m => m.Idcompra == id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idcompra,NomeDaCompra,Valortotal,Valorjuros,Qtdparcelas,Datacompra,Valorparcela,TipoCalculo,Categoria")] Compra compra)
        {
            try
            { // verifica a Id de cada cadastro salvo retornando caso seja existente na base de dados
                if (id != compra.Idcompra)
                {
                    return NotFound();
                }

                if ((ModelState.IsValid) && (compra.Datacompra >= DateTime.Today) && (compra.TipoCalculo == "J.Simples"))
                {

                    try
                    {
                        _context.Update(compra);
                        compra.Valorparcela = compra.Valortotal * compra.Valorjuros + compra.Valortotal;//Formula Juros Simples
                        compra.Valorparcela /= compra.Qtdparcelas;
                        await _context.SaveChangesAsync();
                        TempData["Salvo"] = "A simulação foi salva com sucesso, o valor da sua parcela em " + compra.Qtdparcelas + "X é de R$ " + compra.Valorparcela.ToString("0.00");

                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CompraExists(compra.Idcompra))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }


                else if ((ModelState.IsValid) && (compra.Datacompra >= DateTime.Today) && (compra.TipoCalculo == "J.Composto"))
                {

                    try
                    {
                        _context.Update(compra);
                        double M; //montante
                        double capital = Convert.ToDouble(compra.Valortotal); //capital
                        double taxa = Convert.ToDouble(compra.Valorjuros);//taxa juros
                        double Qtd = Convert.ToDouble(compra.Qtdparcelas);//parcela


                        M = capital * Math.Pow((1 + taxa), Qtd);//Formula Juros Composto


                        compra.Valorparcela = Convert.ToDecimal(M);
                        compra.Valorparcela /= compra.Qtdparcelas;
                        await _context.SaveChangesAsync();
                        TempData["Salvo"] = "A simulação foi salva com sucesso, o valor da sua parcela em " + compra.Qtdparcelas + "X é de R$ " + compra.Valorparcela.ToString("0.00");
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CompraExists(compra.Idcompra))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["ErroSalvar"] = "A data das compras devem ser para hoje ou posteriormente!";
                    return View("Edit");

SimulacaoCompra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Simular & Comprar</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-blue.min.css" />
        <link href="~/mdl/material.min.css" rel="stylesheet" />
        <script src="~/mdl/material.min.js"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" />
        <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Compras" asp-action="Index" class="nav navbar-header img-responsive"><img src="~/images/LOGO.png" alt="logo" /></a>
            </div>
            <div class="navbar-collapse collapse col-lg-10">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Compras" asp-action="Index" class="mdl-typography--font-medium"> Inicio </a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Compras" asp-action="Create" class="mdl-typography--font-medium"> Realizar Simulação</a></li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Simular & Comprar</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery.inputmask/jquery.inputmask.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)



</body>
</html>